# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  app:
    build:
      context: .
    ports:
      - $CLIENT_PORT:$CLIENT_PORT
      - $DOCS_PORT:$DOCS_PORT
      - $API_PORT:$API_PORT
    command: ["/bin/sh", "-c", "pnpm dev"]
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/apps/docs/node_modules
      - /app/apps/frontend/node_modules
      - /app/packages/eslint-config-custom/node_modules
      - /app/packages/tsconfig/node_modules
      - /app/packages/ui/node_modules
    # The section below defines a PostgreSQL
    # database that the application can use. `depends_on` tells Docker Compose to
    # start the database before your application. The `db-data` volume persists the
    # database data between container restarts. The `db-password` secret is used
    # to set the database password. You must create `db/password.txt` and add
    # a password of your choosing to it before running `docker-compose up`.
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.0-alpine3.18
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $DATABASE_NAME -U $DATABASE_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
