services:
  app:
    image: "mcr.microsoft.com/devcontainers/javascript-node:1-18-bullseye"
    volumes:
      - ../:/app:cached
      - pnpm-cache:/app/.pnpm-store
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/apps/docs/node_modules
      - /app/apps/frontend/node_modules
      - /app/packages/eslint-config-custom/node_modules
      - /app/packages/tsconfig/node_modules
      - /app/packages/ui/node_modules
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:16.0-alpine3.18
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  db-data:
  pnpm-cache:
