name: DevSandbox CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run the CI workflow
        run: docker build . --file Dockerfile.ci --tag devsandbox-ci:$(date +%s)
